version: '3.7'

services:
  # Github runner service
  github-runner:
    image: tcardonne/github-runner:v1.3.0
    container_name: github-runner
    restart: always
    environment:
      RUNNER_NAME: server2-runner
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      RUNNER_REPOSITORY_URL: https://github.com/paretl/home_infrastructure
    volumes:
      - /home/lparet/.ssh/id_rsa:/root/.ssh/id_rsa
      - /var/lib/docker/:/var/lib/docker:ro

  # NodeExporter service
  nodeexporter:
    image: prom/node-exporter:v1.0.0-rc.1
    container_name: nodeexporter
    restart: always
    ports:
      - "9100:9100"

  # cAdvisor service
  cadvisor:
    image: google/cadvisor:v0.36.0
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  # Jenkins JNLP agent service
  jenkins-agent:
    image: jenkins/jnlp-slave:4.3-4-alpine
    container_name: jenkins-agent
    restart: always
    environment:
      JENKINS_URL: http://server1:8080
      JENKINS_TUNNEL: server1:50000
      JENKINS_SECRET: ${JENKINS_SECRET}
      JENKINS_AGENT_NAME: server2-agent
      JENKINS_AGENT_WORKDIR: /home/jenkins
    volumes:
      - /home/lparet/.ssh/id_rsa:/home/jenkins/.ssh/id_rsa
