version: '3.7'

services:
  # Nginx Proxy service
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      # I don't use SSL because my internet provider doesn't allow me to use port 443 (SFR)
      # - "443:443"
    volumes:
      - ./nginx/nginx-vhost:/etc/nginx/vhost.d
      - ./nginx/nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:2.257-alpine
    container_name: jenkins
    restart: always
    ports:
      # Open ports 50000 for Jenkins agents communication
      - "50000:50000"
      - "8080:8080"
    environment:
      VIRTUAL_HOST: jenkins.louisparet.co
      VIRTUAL_PORT: 8080
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  # Prometheus service
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    restart: always
    environment:
      VIRTUAL_HOST: prometheus.louisparet.co
      VIRTUAL_PORT: 9090
    volumes:
      - ./prometheus:/etc/prometheus
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  # AlertManager service
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    restart: always
    environment:
      VIRTUAL_HOST: alertmanager.louisparet.co
      VIRTUAL_PORT: 9093
    volumes:
      - ./alertmanager:/etc/alertmanager

  # Grafana service
  grafana:
    image: grafana/grafana:7.2.0
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      VIRTUAL_HOST: grafana.louisparet.co

  # NodeExporter service
  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    restart: always

  # cAdvisor service
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    restart: always
    environment:
      VIRTUAL_HOST: cadvisor.louisparet.co
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  # File Browser service	
  filebrowser:
    image: filebrowser/filebrowser:v2.7.0-alpine
    container_name: filebrowser
    restart: always
    environment:
      VIRTUAL_HOST: filebrowser.louisparet.co
    volumes:
      - ${HOME}:/srv

volumes:
  grafana-storage: