version: '3.7'

services:
  # Nginx Proxy service
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      # I don't use SSL because my internet provider doesn't allow me to use port 443 (SFR)
      # - "443:443"
    volumes:
      - ./nginx/nginx-vhost:/etc/nginx/vhost.d
      - ./nginx/nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:2.229-alpine
    container_name: jenkins
    restart: always
    ports:
      # Open ports 50000 for Jenkins agents communication
      - "50000:50000"
      - "8080:8080"
    environment:
      VIRTUAL_HOST: jenkins.louisparet.co
      VIRTUAL_PORT: 8080

  # Prometheus service
  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    restart: always
    environment:
      VIRTUAL_HOST: prometheus.louisparet.co
      VIRTUAL_PORT: 9090
    volumes:
      - ./prometheus:/etc/prometheus

  # AlertManager service
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    restart: always
    environment:
      VIRTUAL_HOST: alertmanager.louisparet.co
      VIRTUAL_PORT: 9093
    volumes:
      - ./alertmanager:/etc/alertmanager

  # Grafana service
  grafana:
    image: grafana/grafana:6.7.1
    container_name: grafana
    restart: always
    environment:
      VIRTUAL_HOST: grafana.louisparet.co

  # NodeExporter service
  nodeexporter:
    image: prom/node-exporter:v1.0.0-rc.0
    container_name: nodeexporter
    restart: always

  # cAdvisor service
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: always
    environment:
      VIRTUAL_HOST: cadvisor.louisparet.co
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  # File Browser service
  filebrowser:
    image: filebrowser/filebrowser:v2.1.0
    container_name: filebrowser
    restart: always
    environment:
      VIRTUAL_HOST: filebrowser.louisparet.co
    volumes:
      - ${HOME}:/srv

  # MongoDB service
  mongodb:
    image: mongo:4.2.5-bionic
    container_name: mongodb
    restart: always

  # Elasticsearch service
  elasticsearch:
    image: elasticsearch:6.8.7
    container_name: elasticsearch
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  # Graylog service
  graylog:
    image: graylog/graylog:3.2.4-1
    container_name: graylog
    restart: always
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: 'nBkq!^SV8adUD45YDZLl7Wh4s5KvX'
      # Password: 4o5P@j5Ylx@Bz!^YZfbRQ6eoaou3r^
      GRAYLOG_ROOT_PASSWORD_SHA2: 29abad5c1667c35853466225217eef6fb43b0da1e8f472a1e2f0e21f43338907
      GRAYLOG_HTTP_EXTERNAL_URI: http://graylog.louisparet.co/
      # Proxy
      VIRTUAL_HOST: graylog.louisparet.co
      VIRTUAL_PORT: 9000
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
