groups:
- name: RAM
  rules:
  - alert: RAMUsage
    expr: ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes) / (node_memory_MemTotal_bytes) * 100) > 85
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "{{$labels.instance}}: High RAM usage detected"
      description: "{{$labels.instance}}: RAM usage is above 75% (current value is: {{ $value }})."
