# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Rsync
      shell: bash
      run: |
        apt update -y
        apt install -y rsync
        apt install -y ssh-client

    # Runs a single command using the runners shell
    - name: Launch deployment
      shell: bash
      env:
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        JENKINS_SECRET: ${{ secrets.JENKINS_SECRET }}
        GRAYLOG_PASSWORD_SECRET: ${{ secrets.GRAYLOG_PASSWORD_SECRET }}
        GRAYLOG_ROOT_PASSWORD_SHA2: ${{ secrets.GRAYLOG_ROOT_PASSWORD_SHA2 }}
      run: |
        export PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
        export PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
        export GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
        export JENKINS_SECRET=${JENKINS_SECRET}
        export GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
        export GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
        ./deployment.sh
